plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.example.romanticyeojido'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.romanticyeojido"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        def localProperties = new Properties()
        localProperties.load(new FileInputStream(rootProject.file("local.properties")))

        def NAVER_CLIENT_ID = localProperties.getProperty("NAVER_CLIENT_ID")?:""
        def NAVER_CLIENT_SECRET = localProperties.getProperty("NAVER_CLIENT_SECRET")?:""
        def nativeAppKey = localProperties.getProperty("NATIVE_APP_KEY")?:""

        buildConfigField "String", "NAVER_CLIENT_ID", "\"${NAVER_CLIENT_ID}\""
        buildConfigField "String", "NAVER_CLIENT_SECRET", "\"${NAVER_CLIENT_SECRET}\""

        manifestPlaceholders["NAVER_CLIENT_ID"] = NAVER_CLIENT_ID
        manifestPlaceholders["NAVER_CLIENT_SECRET"] = NAVER_CLIENT_SECRET

        buildConfigField "String", "NATIVE_APP_KEY", "\"${nativeAppKey}\""
        manifestPlaceholders["NATIVE_APP_KEY"] = nativeAppKey
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        buildConfig true
        viewBinding true
        dataBinding true
    }
}

dependencies {

    //    카카오 연동
    implementation ("com.kakao.maps.open:android:2.12.8")
    implementation("com.kakao.sdk:v2-user:2.10.0")


    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    //Retrofit
    implementation "com.squareup.retrofit2:retrofit:2.9.0"
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.9.0"

    //Coroutine
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0"

    //naver
    implementation 'com.navercorp.nid:oauth:5.10.0'

    //Kakao
    implementation("com.kakao.sdk:v2-user:2.20.6")

    //Picasso
    implementation 'com.squareup.picasso:picasso:2.8'

    //이미지 Gilde
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    // photo post
    implementation 'com.squareup.retrofit2:retrofit:2.9.0' // 또는 최신 버전
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0' // Gson Converter 의존성
}